### ISSUE TITLE
undefined method `connection' while saving

### ISSUE THREAD

**Issue by AmitPatel-BoTreeConsulting** [norman/friendly_id#737]
I am getting this error with 4.0 gem while saving record. I am on Rails 4.2.5

```
NoMethodError: undefined method `connection' for #<Client:0x00000005281608>
from /home/ubuntu/.rvm/gems/ruby-2.2.2@magnificent/gems/activemodel-4.2.5/lib/active_model/attribute_methods.rb:433:in `method_missing'

```

Here is my configuration

```
class Client < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged
end
```

It works with 5.0.
