### ISSUE TITLE
Incompatibility with Rails3.0.0.beta4

### ISSUE THREAD

**Issue by nono** [norman/friendly_id#68]
Hi, it seems that friendly_id does not work with Rails3.0.0.beta4 because of a commit of a guy called "norman": http://github.com/rails/rails/commit/f3abc8ac36055afed9fcc902c33ee146e066d17a ;-)

The error is :

```
undefined method `apply_mapping' for "ptramo":String
# /home/nono/gem/gems/activesupport-3.0.0.beta4/lib/active_support/multibyte/chars.rb:62:in `__send__'
# /home/nono/gem/gems/activesupport-3.0.0.beta4/lib/active_support/multibyte/chars.rb:62:in `method_missing'
# /home/nono/.bundle/ruby/1.8/bundler/gems/friendly_id-c9c3c7d09845f897608886229f378b98f0ad2481-7fd19b623d0e4879b7de6010c06f231326eda994/lib/friendly_id/slug_string.rb:209:in `downcase!'
```

Can you fix it please?
